#!/bin/sh

if ! hciconfig hci0 > /dev/null 2>&1 ; then
  echo -n "Trying to enable bluetooth... "
  /usr/sbin/rfkill unblock bluetooth
  usleep 1000000
  if ! hciconfig hci0 > /dev/null 2>&1 ; then
    echo "NG"
    exit 1
  fi
  echo "OK"
fi

export BLENO_ADVERTISING_INTERVAL=500
cd /home/root/toiletledbcast
exec node toiletledbcast.js http://192.168.179.2:8000/toilet.json
